"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Moaz Downloader.py']
APP_NAME = "Moaz Video Downloader"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'moaz.icns',
    'packages': ['requests', 'plyer', 'ttkthemes'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Moaz Video Downloader",
        'CFBundleIdentifier': "com.moaz.downloader",
        'CFBundleVersion': "1.0",
        'CFBundleShortVersionString': "1.0",
        'NSHumanReadableCopyright': u"Copyright © 2024, Moaz, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
) 