name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          build_command: buildozer -v android debug
          p4a_branch: develop

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-Android
          path: bin/*.apk

      - name: Create GitHub Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy yt-dlp plyer pyinstaller

      - name: Build Executable
        run: pyinstaller --noconfirm --onefile --windowed --name "MoazDownloader" test1.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-Linux
          path: dist/MoazDownloader

      - name: Create GitHub Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MoazDownloader

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy yt-dlp plyer pyinstaller

      - name: Build Executable
        run: pyinstaller --noconfirm --onefile --windowed --name "MoazDownloader" test1.py

      - name: Zip the .app
        run: ditto -c -k --sequesterRsrc --keepParent dist/MoazDownloader.app dist/MoazDownloader-macOS.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-macOS
          path: dist/MoazDownloader-macOS.zip

      - name: Create GitHub Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MoazDownloader-macOS.zip 