name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          build_command: buildozer -v android debug
          p4a_branch: develop

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-Android
          path: bin/*.apk

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy yt-dlp plyer pyinstaller

      - name: Build Executable
        run: pyinstaller --noconfirm --onefile --windowed --name "MoazDownloader" test1.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-Linux
          path: dist/MoazDownloader

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy yt-dlp plyer pyinstaller

      - name: Build Executable
        run: pyinstaller --noconfirm --onefile --windowed --name "MoazDownloader" test1.py

      - name: Zip the .app
        run: ditto -c -k --sequesterRsrc --keepParent dist/MoazDownloader.app dist/MoazDownloader-macOS.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoazDownloader-macOS
          path: dist/MoazDownloader-macOS.zip

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-android, build-linux, build-macos]
    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: MoazDownloader-Android
          path: ./release/android

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: MoazDownloader-Linux
          path: ./release/linux

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: MoazDownloader-macOS
          path: ./release/macos

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/android/*.apk
            release/linux/MoazDownloader
            release/macos/MoazDownloader-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 